services:
  telegram-bot:
    build: .
    container_name: pdf_banner_bot
    env_file:
      - .env
    restart: unless-stopped
    volumes:
      - ./orders:/app/orders
      - ./bot_data:/app/data
      - ./order_counter.json:/app/order_counter.json
    deploy:
      resources:
        limits:
          memory: 512M
          
