version: '3.8'

services:
  telegram-bot:
    # Собирать образ из Dockerfile в текущей директории
    build: .
    container_name: pdf_banner_bot
    # Передаем переменные окружения из файла .env
    env_file:
      - .env
    # Перезапускать контейнер в случае сбоя
    restart: unless-stopped
